import type {
  ExpressionSpecification,
  LayerSpecification,
  StyleSpecification,
} from "maplibre-gl";

// Spike (#539 section 4): a small hand-written dark style for a self-hosted
// Protomaps PMTiles basemap. It is intentionally not generated by
// @protomaps/basemaps: that package ships ~80 layers across several flavors
// (~440 KB unpacked) and a look that is not the Fiord style the Atlas is tuned
// against, while this covers the few layers the detail view actually shows.
// It uses no icons, so no sprite sheet is needed, and it reads only the
// Protomaps v4 tile schema layers: earth, landcover, water, boundaries, roads
// and places.

export const PMTILES_SOURCE_ID = "startrips-basemap";
export const PMTILES_FONT_STACK = ["Noto Sans Regular"];
export const DEFAULT_PMTILES_GLYPHS_PATH = "/basemap/fonts/{fontstack}/{range}.pbf";

const COLORS = {
  background: "#1c2433",
  earth: "#26324a",
  landcover: "#2b3a4f",
  water: "#141c2a",
  boundary: "#6d7c99",
  roadMajor: "#3f4e6b",
  roadMinor: "#33405a",
  label: "#d9dfe9",
  labelHalo: "#141c2a",
} as const;

/**
 * Turns the configured PMTiles URL into the MapLibre `pmtiles://` source URL.
 * A relative path is resolved against the page so a same-origin archive such as
 * `/basemap/region.pmtiles` works; the protocol handler needs an absolute URL.
 */
export function resolvePmtilesSourceUrl(configuredUrl: string, baseUrl: string): string {
  const trimmed = configuredUrl.trim();
  if (trimmed.startsWith("pmtiles://")) return trimmed;
  return `pmtiles://${new URL(trimmed, baseUrl).href}`;
}

/** Resolves the glyph template against the page, keeping MapLibre's tokens. */
export function resolvePmtilesGlyphsUrl(configuredUrl: string, baseUrl: string): string {
  const template = configuredUrl.trim() || DEFAULT_PMTILES_GLYPHS_PATH;
  if (/^https?:\/\//.test(template)) return template;
  const origin = new URL(baseUrl).origin;
  return `${origin}${template.startsWith("/") ? "" : "/"}${template}`;
}

export function buildPmtilesBasemapStyle({
  pmtilesUrl,
  glyphsUrl,
  baseUrl,
  labelTextField,
}: {
  pmtilesUrl: string;
  glyphsUrl: string;
  baseUrl: string;
  labelTextField: ExpressionSpecification;
}): StyleSpecification {
  const source = PMTILES_SOURCE_ID;
  const layers: LayerSpecification[] = [
    { id: "background", type: "background", paint: { "background-color": COLORS.background } },
    {
      id: "earth",
      type: "fill",
      source,
      "source-layer": "earth",
      paint: { "fill-color": COLORS.earth },
    },
    {
      id: "landcover",
      type: "fill",
      source,
      "source-layer": "landcover",
      paint: { "fill-color": COLORS.landcover, "fill-opacity": 0.5 },
    },
    {
      id: "water",
      type: "fill",
      source,
      "source-layer": "water",
      paint: { "fill-color": COLORS.water },
    },
    {
      id: "roads-minor",
      type: "line",
      source,
      "source-layer": "roads",
      minzoom: 10,
      filter: ["in", ["get", "kind"], ["literal", ["minor_road", "path"]]],
      paint: { "line-color": COLORS.roadMinor, "line-width": 0.6 },
    },
    {
      id: "roads-major",
      type: "line",
      source,
      "source-layer": "roads",
      filter: ["in", ["get", "kind"], ["literal", ["highway", "major_road"]]],
      paint: {
        "line-color": COLORS.roadMajor,
        "line-width": ["interpolate", ["linear"], ["zoom"], 6, 0.6, 14, 2.4],
      },
    },
    {
      id: "boundaries",
      type: "line",
      source,
      "source-layer": "boundaries",
      filter: ["in", ["get", "kind"], ["literal", ["country", "region"]]],
      paint: { "line-color": COLORS.boundary, "line-width": 0.8, "line-dasharray": [3, 2] },
    },
    {
      id: "places",
      type: "symbol",
      source,
      "source-layer": "places",
      filter: ["in", ["get", "kind"], ["literal", ["country", "region", "locality"]]],
      layout: {
        "text-field": labelTextField,
        "text-font": PMTILES_FONT_STACK,
        "text-size": [
          "match",
          ["get", "kind"],
          "country", 15,
          "region", 13,
          12,
        ],
        "text-max-width": 8,
        "symbol-sort-key": ["to-number", ["get", "min_zoom"], 99],
      },
      paint: {
        "text-color": COLORS.label,
        "text-halo-color": COLORS.labelHalo,
        "text-halo-width": 1.2,
      },
    },
  ];

  return {
    version: 8,
    glyphs: resolvePmtilesGlyphsUrl(glyphsUrl, baseUrl),
    sources: {
      [source]: {
        type: "vector",
        url: resolvePmtilesSourceUrl(pmtilesUrl, baseUrl),
        attribution: "© OpenStreetMap contributors · Protomaps",
      },
    },
    layers,
  };
}
